
# todo ...

stages:
  get_links:
    cmd: python3 download/get_links.py
    outs:
      - download/json/links.json
  get_imgs:
    cmd: python3 download/get_imgs.py
    outs:
      - download/dataset/
